### PR TITLE
Added Kustomize for controller, sidecar & CRDs

### PR DESCRIPTION
**Pull request by tparikh**
Signed-off-by: Tejas Parikh <tejas@tejasparikh.com>

### CODE REVIEW

**Comment by NicolasT** [comment]
I left a review of this code at https://github.com/container-object-storage-interface/cosi-controller-manager/pull/9#pullrequestreview-546302155, would rather not duplicate those comments here :wink:

**Comment by tparikh** [comment]
> I left a review of this code at [container-object-storage-interface/cosi-controller-manager#9 (review)](https://github.com/container-object-storage-interface/cosi-controller-manager/pull/9#pullrequestreview-546302155), would rather not duplicate those comments here 😉

I have created following issues for comments that are still unresolved on the old PR
- https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/issues/13
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/19
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/21
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/20

**Comment by wlan0** [comment]
@NicolasT We would appreciate any contribution from your expertise for the issues mentioned above.

**Review by wlan0 — APPROVED** [review]

**Pull request merged**
