### PR TITLE
Refactor Kustomize deployment

### PR DESCRIPTION
**Pull request by NicolasT**
First stab at some of the changes suggested in https://github.com/container-object-storage-interface/cosi-controller-manager/pull/9:

- Add some standard labels to all deployed object
- Split out a `base` layer and a `fullstack` layer on top of it
- Don't force `IfNotPresent` `imagePullPolicy` which one potentially doesn't want for `latest` images (we could patch this in a `dev` layer?)
- Don't override image names with the image that's already hard-coded in the basic manifest

See: https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/23
See: https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/21
See: https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/11

### CODE REVIEW

**Comment by NicolasT** [comment]
Looks like I can't add this PR to a specific (GitHub) `Milestone` or `Project` myself, so this won't show up in the project planning boards for now.

**Comment by NicolasT** [comment]
The original deployment manifests use two namespaces to deploy the stack, one for the controller (`objectstorage-system`), one for the provisioner (`objectstorage-provisioner-ns`). Is this a separation we want to keep? I get how in production clusters one may want to run them in separate namespaces, though for the `fullstack` layer, which includes the controller as well as the sample-provisioner, I'd suggest to keep things together.

**Comment by NicolasT** [comment]
For reference, here's a diff between a rendering of the manifest as found in the `master` branch at this point in time, and the `deploy/fullstack` layer as introduced by this PR:

```diff
--- orig        2020-12-17 18:14:01.642989168 +0000                                                                                                                                                                                                                                                                           
+++ new 2020-12-17 18:14:14.028253760 +0000                                                                                                                                                                                                                                                                                   
@@ -554,12 +554,22 @@                                                                                                                                                                                                                                                                                                         
 apiVersion: v1                                                                                                                                                                                                                                                                                                               
 kind: ServiceAccount                                                                                                                                                                                                                                                                                                         
 metadata:                                                                                                                                                                                                                                                                                                                    
+  labels:                                                                                                                                                                                                                                                                                                                    
+    app.kubernetes.io/component: controller                                                                                                                                                                                                                                                                                  
+    app.kubernetes.io/name: container-object-storage-interface-controller                                                                                                                                                                                                                                                    
+    app.kubernetes.io/part-of: container-object-storage-interface                                                                                                                                                                                                                                                            
+    app.kubernetes.io/version: main                                                                                                                                                                                                                                                                                          
   name: objectstorage-controller-sa                                                                                                                                                                                                                                                                                          
   namespace: objectstorage-system                                                                                                                                                                                                                                                                                            
 ---                                                                                                                                                                                                                                                                                                                          
 apiVersion: rbac.authorization.k8s.io/v1                                                                                                                                                                                                                                                                                     
 kind: Role                                                                                                                                                                                                                                                                                                                   
 metadata:                                                                                                                                                                                                                                                                                                                    
+  labels:                                                                                                                                                                                                                                                                                                                    
+    app.kubernetes.io/component: controller                                                                                                                                                                                                                                                                                  
+    app.kubernetes.io/name: container-object-storage-interface-controller                                                                                                                                                                                                                                                    
+    app.kubernetes.io/part-of: container-object-storage-interface                                                                                                                                                                                                                                                            
+    app.kubernetes.io/version: main                                                                                                                                                                                                                                                                                          
   name: objectstorage-controller                                                                                                                                                                                                                                                                                             
   namespace: objectstorage-system                                                                                                                                                                                                                                                                                            
 rules:
@@ -578,6 +588,11 @@
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
+  labels:
+    app.kubernetes.io/component: controller
+    app.kubernetes.io/name: container-object-storage-interface-controller
+    app.kubernetes.io/part-of: container-object-storage-interface
+    app.kubernetes.io/version: main
   name: objectstorage-controller-role
 rules:
 - apiGroups:
@@ -623,6 +638,11 @@
 apiVersion: rbac.authorization.k8s.io/v1
 kind: RoleBinding
 metadata:
+  labels:
+    app.kubernetes.io/component: controller
+    app.kubernetes.io/name: container-object-storage-interface-controller
+    app.kubernetes.io/part-of: container-object-storage-interface
+    app.kubernetes.io/version: main
   name: objectstorage-controller
   namespace: objectstorage-system
 roleRef:
@@ -637,6 +657,11 @@
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
+  labels:
+    app.kubernetes.io/component: controller
+    app.kubernetes.io/name: container-object-storage-interface-controller
+    app.kubernetes.io/part-of: container-object-storage-interface
+    app.kubernetes.io/version: main
   name: system:objectstorage-controller
 roleRef:
   apiGroup: rbac.authorization.k8s.io
@@ -703,13 +728,20 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
+  labels:
+    app.kubernetes.io/component: controller
+    app.kubernetes.io/name: container-object-storage-interface-controller
+    app.kubernetes.io/part-of: container-object-storage-interface
+    app.kubernetes.io/version: main
   name: objectstorage-controller
   namespace: objectstorage-system
 spec:
   replicas: 1
   selector:
     matchLabels:
-      app: objectstorage-controller
+      app.kubernetes.io/component: controller
+      app.kubernetes.io/name: container-object-storage-interface-controller
+      app.kubernetes.io/part-of: container-object-storage-interface
   strategy:
     rollingUpdate:
       maxSurge: 1
@@ -717,10 +749,12 @@
   template:
     metadata:
       labels:
-        app: objectstorage-controller
+        app.kubernetes.io/component: controller
+        app.kubernetes.io/name: container-object-storage-interface-controller
+        app.kubernetes.io/part-of: container-object-storage-interface
+        app.kubernetes.io/version: main
     spec:
       containers:
       - image: quay.io/containerobjectstorage/objectstorage-controller:latest
-        imagePullPolicy: IfNotPresent
         name: objectstorage-controller
       serviceAccountName: objectstorage-controller-sa
```

**Comment by tparikh** [comment]
/lgtm

@wlan0 and @brahmaroutu thoughts on namespace changes?

**Comment by NicolasT** [comment]
> @wlan0 and @brahmaroutu thoughts on namespace changes?

Note current PR doesn't make any changes to namespaces being used (except for *creating* the one the sample provisioner wants to be deployed in, though one could argue that one should get its own Kustomize in its repo which we can then reference...).

**Comment by wlan0** [comment]
Yeah you’ve just removed the hard coded namespace.

**Review by wlan0 — APPROVED** [review]

**Pull request merged**
