### PR TITLE
Added push to Cloudbuild.yaml and swapped out quay.io with gcr repo

### PR DESCRIPTION
**Pull request by aarongalang**
Added a push step to the Cloudbuild.yaml file and changed references to quay.io repo in Makefile and build.make to the gcr.io repo. Does build, but I can't test if pushing works without proper permissions.

### CODE REVIEW

**Comment by xing-yang** [comment]
/assign @pohly 
@pohly Can you help take a look?

**Comment by xing-yang** [comment]
@aarongalang Please sign CLA.

**Comment by pohly** [comment]
This repo seems to use csi-release-tools already. Is there a reason to not also use the cloudbuild.yaml from there?

**Comment by xing-yang** [comment]
> This repo seems to use csi-release-tools already. Is there a reason to not also use the cloudbuild.yaml from there?

@pohly COSI has its own release-tools here: https://github.com/kubernetes-sigs/container-object-storage-interface-spec/tree/master/release-tools

**Comment by pohly** [comment]
That looks like a fork of https://github.com/kubernetes-csi/csi-release-tools? It's the exact same files.

Anyway, I don't think I can help here.

**Comment by xing-yang** [comment]
> That looks like a fork of https://github.com/kubernetes-csi/csi-release-tools? It's the exact same files.
> Anyway, I don't think I can help here.

@pohly Initially it was a copy from csi-release-tools, but later on they removed lots of things because of the differences between the repos.

**Comment by xing-yang** [comment]
@aarongalang Can you resolve the merge conflicts?

**Pull request merged**
